[package]
name = "rgb-ui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rgb-core = { path = "../rgb-core" }
rgb-life = { path = "../rgb-life" }
bevy.workspace = true
