[package]
name = "query-dsl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Flecs-like query DSL parser for RGB ECS"

[dependencies]

[dev-dependencies]

[lints]
workspace = true
