[package]
name = "rgb-life"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rgb-core = { path = "../rgb-core" }
flecs_ecs.workspace = true
