[package]
name = "module-play"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
flecs_ecs.workspace = true
module-loader = { path = "../../module-loader" }
module-network-components = { path = "../network-components" }
module-login = { path = "../login" }
module-chunk = { path = "../chunk" }
module-time-components = { path = "../time-components" }
mc-protocol = { path = "../../mc-protocol" }
mc-data = { path = "../../mc-data" }
byteorder.workspace = true
bytes.workspace = true
eyre.workspace = true
tracing.workspace = true

[lints]
workspace = true
