[package]
name = "module-listener"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "TCP listener module - spawns async network server"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
flecs_ecs.workspace = true
module-loader = { path = "../../module-loader" }
module-network-components = { path = "../network-components" }
mc-protocol = { path = "../../mc-protocol" }
bytes.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
eyre.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros"] }

[lints]
workspace = true
