[package]
name = "module-time-components"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
flecs_ecs.workspace = true

[lints]
workspace = true
