[package]
name = "skript-lang"
description = "A Skript language parser and AST"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chumsky = { path = "/Users/andrewgazelka/Projects/chumsky", features = ["std", "stacker"] }

[dev-dependencies]
insta = "1"

[lints]
workspace = true
