[package]
name = "module-network"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Network module - handles packet ingress/egress and connection management"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
flecs_ecs.workspace = true
bytes.workspace = true
crossbeam-channel.workspace = true
module-loader = { path = "../../module-loader" }
module-network-components = { path = "../network-components" }
tracing.workspace = true

[lints]
workspace = true
