[package]
name = "module-time-systems"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
# crate-type = ["dylib", "rlib"]  # Disabled for static linking

[dependencies]
flecs_ecs.workspace = true
module-loader = { path = "../../module-loader" }
module-time-components = { path = "../time-components" }

[lints]
workspace = true
