[package]
name = "module-chunk-components"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
# rlib (default) - component definitions, statically linked

[dependencies]
flecs_ecs.workspace = true
module-loader = { path = "../../module-loader" }
bytes.workspace = true

[lints]
workspace = true
