[package]
name = "module-skript"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
skript-lang = { path = "../skript-lang" }
flecs_ecs.workspace = true
tracing.workspace = true

[lints]
workspace = true
